spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sugang
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
